version: '3.8'
services:
  mongo:
    image: mongo:5.0
    restart: always
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    restart: always

  graylog:
    image: graylog/graylog:5.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=${GRAYLOG_PASSWORD_SECRET}
      - GRAYLOG_ROOT_PASSWORD_SHA2=${GRAYLOG_ROOT_PASSWORD_SHA2}
      - GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_HTTP_EXTERNAL_URI}
    depends_on:
      - mongo
      - opensearch
    ports:
      - "9000:9000"       # Web UI
      - "12201:12201/tcp" # GELF TCP input
      - "1514:1514/tcp"   # Syslog TCP
    restart: always
