services:
  - type: compose
    name: graylog-stack
    repo: https://github.com/<you>/graylog-stack
    envVars:
      - key: GRAYLOG_PASSWORD_SECRET
        value: s0m3S3cr3tStr1ng
      - key: GRAYLOG_ROOT_PASSWORD_SHA2
        value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - key: GRAYLOG_HTTP_EXTERNAL_URI
        value: https://graylog.<your-domain>.com/
    routes:
      - type: http
        port: 9000
      - type: tcp
        port: 12201
      - type: tcp
        port: 1514
